apiVersion: v1
kind: Service
metadata:
  name: ftps-srv
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  ports:
    - name: command
      protocol: TCP
      port: 21
      targetPort: 21
    - name: data
      protocol: TCP
      port: 20
      targetPort: 20
    - name: pss-port
      protocol: TCP
      port: 12345
      targetPort: 12345
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-dep
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          image: ftps_im
          imagePullPolicy: Never
          ports:
            - containerPort: 20
            - containerPort: 21
            - containerPort: 12345


