apiVersion: v1
kind: Service
metadata:
  name: nginx-srv
  labels:
    app: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      containers:
        - name: nginx
          image: ngx_im
          imagePullPolicy: Never
          ports:
            - containerPort: 80
            - containerPort: 443
