apiVersion: v1
kind: Service
metadata:
  name: wp-svc
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  ports:
    - port: 5050
      targetPort: 5050
  selector:
    app: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-dep
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      restartPolicy: Always
      containers:
      - image: wp_im
        name: wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          name: wordpress

